### PR TITLE
add null filter support

### PR DESCRIPTION
**Pull request by maceonrails**
usage { field: { null: true } } for is null filter and { field: { null: false } } for not null filter

### CODE REVIEW

**Comment by vasilakisfil** [comment]
Hi! Thanks for the PR. Could you update the readme and show how it works :)

**Comment by maceonrails** [comment]
Hi, I've update the readme file. thanks :)

**Comment by vasilakisfil** [comment]
I can see you check `params[:null] == true`. Will that always work ? I would use ActiveRecord::Type::Boolean.new.type_cast_from_database to be sure that all 't', '1', 1, 'true', 'TRUE' and boolean true work :)

I can fix it later tonight once I merge no worries :)

**Comment by maceonrails** [comment]
yea i have test it and it work both for true and false value, but if you think it better to use type cast to make sure it work, thats good :)

**Comment by vasilakisfil** [comment]
@maceonrails it seems good! I thought I could branch in your branch but it's a pull request from another repo so it's impossible :)

Can you add ActiveRecord::Type::Boolean.new.type_cast_from_database in your code and squash your commits to 1 commit ? Then I will merge instantly :)

**Comment by vasilakisfil** [comment]
Not sure how I missed that, merged :)

**Pull request merged**
